using Application.MainBoundedContext.DTO; using Application.MainBoundedContext.Services; using Application.MainBoundedContext.AccountsModule.Services; using Domain.MainBoundedContext.InventoryModule.Aggregates.AssetAgg; using Domain.MainBoundedContext.InventoryModule.Aggregates.AssetTypeAgg; using Domain.Seedwork; using Infrastructure.Crosscutting.Framework.Adapter; using Infrastructure.Crosscutting.Framework.Utils; using Numero3.EntityFramework.Interfaces; using System; using System.Collections.Generic; using System.Threading.Tasks;
namespace Application.MainBoundedContext.InventoryModule.Services { public class AssetAppService:IAssetAppService {
readonly IDbContextScopeFactory scopes; readonly IRepository<Asset> repo; readonly IRepository<AssetType> types; readonly IFinancialsService financials; readonly IJournalAppService journals;
public AssetAppService(IDbContextScopeFactory s,IRepository<Asset> r,IRepository<AssetType> t,IFinancialsService f,IJournalAppService j){scopes=s;repo=r;types=t;financials=f;journals=j;}
void Valid(AssetDTO d){if(d==null||String.IsNullOrWhiteSpace(d.Name)||d.AssetTypeId==Guid.Empty||d.BranchId==Guid.Empty||d.GLAccountId==Guid.Empty)throw new InvalidOperationException("Name, asset type and branch are required.");if(d.PurchasePrice<=0||d.ResidualValue<0||d.ResidualValue>=d.PurchasePrice)throw new InvalidOperationException("Residual value must be non-negative and below purchase price.");if(d.DepreciationStartDate<d.AcquisitionDate)throw new InvalidOperationException("Depreciation cannot start before acquisition.");}
async Task<AssetType> GetType(Guid id,ServiceHeader h){var t=await types.GetAsync(id,h);if(t==null)throw new InvalidOperationException("Asset type not found.");return t;}
Asset Make(AssetDTO d,AssetType t){var x=AssetFactory.Create(d.Name,d.Remarks,t.Name,d.Supplier,d.Department,d.PicturePath,d.GLAccount,d.SerialNumber,d.Manufacturer,d.Model,d.TagNumber,d.Location,d.PurchasePrice,d.ResidualValue);x.AssetTypeId=t.Id;x.BranchId=d.BranchId;x.GLAccountId=d.GLAccountId;x.AcquisitionDate=d.AcquisitionDate;x.DepreciationStartDate=d.DepreciationStartDate;return x;}
public async Task<PageCollectionInfo<AssetDTO>> FindAsync(string q,int p,int z,ServiceHeader h){using(scopes.CreateReadOnly())return await repo.AllMatchingPagedAsync<AssetDTO>(AssetSpecifications.Find(q),p,z,new List<string>{"SequentialId"},true,h);} public async Task<AssetDTO> FindAsync(Guid id,ServiceHeader h){using(scopes.CreateReadOnly())return await repo.GetAsync<AssetDTO>(id,h);}
public async Task<AssetDTO> AddAsync(AssetDTO d,ServiceHeader h){Valid(d);using(var s=scopes.Create()){var x=Make(d,await GetType(d.AssetTypeId,h));repo.Add(x,h);return await s.SaveChangesAsync(h)>0?x.ProjectedAs<AssetDTO>():null;}}
public async Task<bool> UpdateAsync(AssetDTO d,ServiceHeader h){Valid(d);using(var s=scopes.Create()){var p=await repo.GetAsync(d.Id,h);if(p==null)return false;var x=Make(d,await GetType(d.AssetTypeId,h));x.AccumulatedDepreciation=p.AccumulatedDepreciation;x.LastDepreciationDate=p.LastDepreciationDate;x.ChangeCurrentIdentity(p.Id,p.SequentialId,p.CreatedBy,p.CreatedDate);repo.Merge(p,x,h);return await s.SaveChangesAsync(h)>0;}}
decimal Calc(Asset a,AssetType t,DateTime d){var start=new DateTime(a.DepreciationStartDate.Year,a.DepreciationStartDate.Month,1);var period=new DateTime(d.Year,d.Month,1);if(period<start||(a.LastDepreciationDate.HasValue&&period<=a.LastDepreciationDate.Value))throw new InvalidOperationException("Depreciation period is invalid or already posted.");var n=(period.Year-start.Year)*12+period.Month-start.Month+1;var life=t.UsefulLife*12;if(n>life)return 0;double v;switch((DepreciationMethod)t.DepreciationMethod){case DepreciationMethod.SYD:v=financials.SYD((double)a.PurchasePrice,(double)a.ResidualValue,life,n);break;case DepreciationMethod.DB:v=financials.DB((double)a.PurchasePrice,(double)a.ResidualValue,life,n,12);break;case DepreciationMethod.DDB:v=financials.DDB((double)a.PurchasePrice,(double)a.ResidualValue,life,n);break;case DepreciationMethod.VDB:v=financials.VDB((double)a.PurchasePrice,(double)a.ResidualValue,life,n,2);break;default:v=financials.SLN((double)a.PurchasePrice,(double)a.ResidualValue,life);break;}return Math.Max(0,Math.Min(a.PurchasePrice-a.ResidualValue-a.AccumulatedDepreciation,Math.Round((decimal)v,2)));}
public async Task<AssetDepreciationDTO> PreviewDepreciationAsync(Guid id,DateTime d,ServiceHeader h){using(scopes.CreateReadOnly()){var a=await repo.GetAsync(id,h);if(a==null)return null;var v=Calc(a,await GetType(a.AssetTypeId,h),d);return new AssetDepreciationDTO{AssetId=id,PeriodDate=d,Amount=v,AccumulatedDepreciation=a.AccumulatedDepreciation+v,NetBookValue=a.PurchasePrice-a.AccumulatedDepreciation-v};}}
public async Task<AssetDepreciationDTO> PostDepreciationAsync(Guid id,DateTime d,ServiceHeader h){using(var s=scopes.Create()){var a=await repo.GetAsync(id,h);if(a==null)return null;var t=await GetType(a.AssetTypeId,h);if(t.DepreciationExpenseAccountId==Guid.Empty||t.AccumulatedDepreciationAccountId==Guid.Empty)throw new InvalidOperationException("Configure depreciation G/L accounts first.");var v=Calc(a,t,d);if(v<=0)throw new InvalidOperationException("No depreciation remains.");var pd=new DateTime(d.Year,d.Month,DateTime.DaysInMonth(d.Year,d.Month));var journal=journals.AddNewJournal(a.BranchId,null,v,"Asset depreciation",a.Name,String.Format("ASSET-DEPR-{0}-{1:yyyyMM}",a.Id,pd),30013,(int)SystemTransactionCode.AssetDepreciation,pd,t.AccumulatedDepreciationAccountId,t.DepreciationExpenseAccountId,h,false);if(journal==null)throw new InvalidOperationException("Depreciation journal could not be posted.");a.AccumulatedDepreciation+=v;a.LastDepreciationDate=new DateTime(d.Year,d.Month,DateTime.DaysInMonth(d.Year,d.Month));await s.SaveChangesAsync(h);return new AssetDepreciationDTO{AssetId=id,PeriodDate=a.LastDepreciationDate.Value,Amount=v,AccumulatedDepreciation=a.AccumulatedDepreciation,NetBookValue=a.PurchasePrice-a.AccumulatedDepreciation,Posted=true};}}
} }
